name: "Deploy Wpf App"

on:
  push:
    tags:
      - "deploy/v*"

env:
  PROJECT_PATH: WpfApp1/WpfApp1.csproj

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - uses: nuget/setup-nuget@v2
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        # run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore -p:SourceLinkEnabled=true
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

      - name: Publish to NuGet.org
        run: nuget push **\*.nupkg -NonInteractive -SkipDuplicate -Source 'https://api.nuget.org/v3/index.json'

      # - uses: actions/create-release@v1
      #   id: create_release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: ${{ github.ref }}

      # - uses: csexton/release-asset-action@v2
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     pattern: WpfApp1/bin/Release/net8.0/win-x64/publish/*.exe
      #     release-url: ${{ steps.create_release.outputs.upload_url }}
